### ISSUE TITLE
FAlta de experiencia con node js

### ISSUE THREAD

**Issue by nbaglietto** [ParalelniPolis/rfid-access-system-api-2#1]
Hola estoy tratando de hacer funcionar este proyecto en una vm virtualbox con ubuntu 16 server.

al querer ejecutar npm start el sistema me responde:
Error: ENOENT: no such file or directory, scandir '/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.getInstalledBinaries (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/app.js:19:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rfid-access-system-api-2@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rfid-access-system-api-2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-04T19_27_42_590Z-debug.log
root@wemos:/home/sistemas/rfid-access-system-api-2#

**Comment by pajasevi** [comment]
As you can see, the `node-sass` dependency seems to be missing. Be sure to install dependencies properly.
