### ISSUE TITLE
npm test

### ISSUE THREAD

**Issue by nbaglietto** [ParalelniPolis/rfid-access-system-api-2#2]
root@wemos:/home/sistemas/rfid-access-system-api-2# npm test

> rfid-access-system-api-2@1.0.0 test /home/sistemas/rfid-access-system-api-2
> mocha --reporter spec

fs.js:928
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.getInstalledBinaries (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/node_modules/node-sass-middleware/middleware.js:3:12)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/app.js:19:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/test/app.js:2:13)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at /home/sistemas/rfid-access-system-api-2/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/sistemas/rfid-access-system-api-2/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/sistemas/rfid-access-system-api-2/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/home/sistemas/rfid-access-system-api-2/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
npm ERR! Test failed.  See above for more details.
root@wemos:/home/sistemas/rfid-access-system-api-2#

**Comment by pajasevi** [comment]
Closing this - same issue as #1
